name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: |
        cd server && npm install
        cd ../client && npm install
        npx playwright install --with-deps
        
    - name: Start backend server
      run: |
        cd server
        npm start &
        sleep 5
        
    - name: Start frontend
      run: |
        cd client
        npm start &
        sleep 10
        
    - name: Run Playwright tests
      run: |
        cd client
        npx playwright test
        
    - name: Generate Allure Report
      if: always()
      run: |
        cd client
        npx allure generate allure-results -o allure-report --clean
        
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: client/allure-report
        retention-days: 30
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: client/playwright-report/
        retention-days: 30 