name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: |
        cd server && npm install
        cd ../client && npm install
        npx playwright install --with-deps
        
    - name: Start backend server
      run: |
        cd server
        npm start &
        sleep 5
        
    - name: Start frontend
      run: |
        cd client
        npm start &
        sleep 10
        
    - name: Run Playwright tests
      run: |
        cd client
        npx playwright test
        
    - name: Generate Allure Report
      if: always()
      run: |
        cd client
        npx allure generate allure-results -o allure-report --clean
        
    - name: Deploy Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: client/allure-report 