name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies
      run: |
        cd server && npm install
        cd ../client && npm install
        npx playwright install --with-deps
        
    - name: Start backend server
      run: |
        cd server
        npm start &
        sleep 5
        
    - name: Start frontend
      run: |
        cd client
        npm start &
        sleep 10
        
    - name: Run Playwright tests
      run: |
        cd client
        npx playwright test
        
    - name: Generate Allure Report
      if: always()
      run: |
        cd client
        npx allure generate allure-results -o allure-report --clean
        
    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v2
        
    - name: Upload Allure Report artifact
      if: always()
      uses: actions/upload-pages-artifact@v2
      with:
        path: client/allure-report
        
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: client/playwright-report/
        retention-days: 30 